###########################################################################
# ğŸ¢ íšŒì‚¬ í™˜ê²½ ì „ìš© ì„¤ì • íŒŒì¼
# - ê³µí†µ(application.yml)ì˜ ì„¤ì •ì„ ê·¸ëŒ€ë¡œ ìƒì†ë°›ê³ 
# - ì•„ë˜ ê°’ë“¤ë§Œ ì§‘ í™˜ê²½ì— ë§ê²Œ 'ë®ì–´ì“°ê¸°(override)' í•©ë‹ˆë‹¤.
###########################################################################

###########################################################################
# ğŸ Python ì‹¤í–‰ í™˜ê²½ ì„¤ì • (ì§‘)
###########################################################################
python:

  # âœ… Python ì‹¤í–‰ íŒŒì¼ ê²½ë¡œ - ì§‘ PC ê¸°ì¤€
  # - Windows ê¸°ë³¸ ì„¤ì¹˜ ê²½ë¡œ
  # - pip íŒ¨í‚¤ì§€ë„ ì´ í™˜ê²½ì— ì„¤ì¹˜ë˜ì–´ ìˆì–´ì•¼ í•¨
  executable:
    path: C:/Users/User/AppData/Local/Programs/Python/Python310/python.exe

  # âœ… MyBaseLinkV2 í”„ë¡œì íŠ¸ì˜ ë£¨íŠ¸ ê²½ë¡œ(ì§‘)
  # - python script ëŠ” ì´ ê²½ë¡œ ê¸°ë°˜ìœ¼ë¡œ ì‹¤í–‰ë¨
  root:
    path: C:/LocBootProject/workspace/MyBaseLinkV2

  # âœ… Python ìŠ¤í¬ë¦½íŠ¸ ê²½ë¡œ ì„¤ì •
  # - ìì‹ ì„¤ì •ë“¤ì€ root.path ë¥¼ ê¸°ë°˜ìœ¼ë¡œ ê´€ë¦¬
  working:
    dir: "${python.root.path}/python"  # python í´ë” ê¸°ì¤€ ì‹¤í–‰
  update_stock_listing:
    path: "${python.root.path}/python/stock/py/update_stock_listing.py"
  stock:
    stock_listing:
      path: "${python.root.path}/python/stock/stock_list/stock_listing.json"


###########################################################################
# ğŸ˜ PostgreSQL DB ì ‘ì† ì„¤ì • (ì§‘)
# - DB ì£¼ì†Œ ë° ê³„ì • ë¹„ë°€ì •ë³´ê°€ ìœ„ì¹˜
###########################################################################
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybaselink_db
    username: mybaseuser
    password: mybaseuser1234

